BEGIN;

DROP TABLE IF EXISTS daily_assignments CASCADE;
DROP TABLE IF EXISTS problem_completions CASCADE;
DROP TABLE IF EXISTS problem_concepts CASCADE;
DROP TABLE IF EXISTS user_concept_preferences CASCADE;
DROP TABLE IF EXISTS problems CASCADE;
DROP TABLE IF EXISTS concepts CASCADE;
DROP TABLE IF EXISTS users CASCADE;

COMMIT;