--
-- PostgreSQL database dump
--

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: problems; Type: TABLE DATA; Schema: public; Owner: queue_up
--

INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (1, 'contains-duplicate', 'Contains Duplicate', 'Easy', 'https://leetcode.com/problems/contains-duplicate/', 'NEETCODE_150', 1, true, '{ARRAY_HASHING}', '2026-04-02 20:19:13.375622+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (2, 'valid-anagram', 'Valid Anagram', 'Easy', 'https://leetcode.com/problems/valid-anagram/', 'NEETCODE_150', 2, true, '{ARRAY_HASHING}', '2026-04-02 20:19:13.379089+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (3, 'two-sum', 'Two Sum', 'Easy', 'https://leetcode.com/problems/two-sum/', 'NEETCODE_150', 3, true, '{ARRAY_HASHING}', '2026-04-02 20:19:13.381425+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (4, 'group-anagrams', 'Group Anagrams', 'Medium', 'https://leetcode.com/problems/group-anagrams/', 'NEETCODE_150', 4, true, '{ARRAY_HASHING}', '2026-04-02 20:19:13.383796+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (5, 'top-k-frequent-elements', 'Top K Frequent Elements', 'Medium', 'https://leetcode.com/problems/top-k-frequent-elements/', 'NEETCODE_150', 5, true, '{ARRAY_HASHING}', '2026-04-02 20:19:13.386157+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (6, 'product-of-array-except-self', 'Product of Array Except Self', 'Medium', 'https://leetcode.com/problems/product-of-array-except-self/', 'NEETCODE_150', 6, true, '{ARRAY_HASHING}', '2026-04-02 20:19:13.388625+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (7, 'valid-sudoku', 'Valid Sudoku', 'Medium', 'https://leetcode.com/problems/valid-sudoku/', 'NEETCODE_150', 7, true, '{ARRAY_HASHING}', '2026-04-02 20:19:13.390932+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (8, 'longest-consecutive-sequence', 'Longest Consecutive Sequence', 'Medium', 'https://leetcode.com/problems/longest-consecutive-sequence/', 'NEETCODE_150', 8, true, '{ARRAY_HASHING}', '2026-04-02 20:19:13.393313+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (9, 'implement-stack-using-queues', 'Implement Stack using Queues', 'Easy', 'https://leetcode.com/problems/implement-stack-using-queues/', 'NEETCODE_150', 9, true, '{QUEUE}', '2026-04-02 20:19:13.395612+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (10, 'moving-average-from-data-stream', 'Moving Average from Data Stream', 'Easy', 'https://leetcode.com/problems/moving-average-from-data-stream/', 'NEETCODE_150', 10, true, '{QUEUE}', '2026-04-02 20:19:13.397951+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (11, 'design-circular-queue', 'Design Circular Queue', 'Medium', 'https://leetcode.com/problems/design-circular-queue/', 'NEETCODE_150', 11, true, '{QUEUE}', '2026-04-02 20:19:13.400473+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (12, 'number-of-recent-calls', 'Number of Recent Calls', 'Easy', 'https://leetcode.com/problems/number-of-recent-calls/', 'NEETCODE_150', 12, true, '{QUEUE}', '2026-04-02 20:19:13.402737+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (13, 'valid-palindrome', 'Valid Palindrome', 'Easy', 'https://leetcode.com/problems/valid-palindrome/', 'NEETCODE_150', 13, true, '{TWO_POINTERS}', '2026-04-02 20:19:13.405125+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (14, 'two-sum-ii-input-array-is-sorted', 'Two Sum II', 'Medium', 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/', 'NEETCODE_150', 14, true, '{TWO_POINTERS}', '2026-04-02 20:19:13.407425+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (15, '3sum', '3Sum', 'Medium', 'https://leetcode.com/problems/3sum/', 'NEETCODE_150', 15, true, '{TWO_POINTERS}', '2026-04-02 20:19:13.40973+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (16, 'container-with-most-water', 'Container With Most Water', 'Medium', 'https://leetcode.com/problems/container-with-most-water/', 'NEETCODE_150', 16, true, '{TWO_POINTERS}', '2026-04-02 20:19:13.412081+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (17, 'trapping-rain-water', 'Trapping Rain Water', 'Hard', 'https://leetcode.com/problems/trapping-rain-water/', 'NEETCODE_150', 17, true, '{TWO_POINTERS}', '2026-04-02 20:19:13.41428+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (18, 'best-time-to-buy-and-sell-stock', 'Best Time to Buy and Sell Stock', 'Easy', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', 'NEETCODE_150', 18, true, '{SLIDING_WINDOW}', '2026-04-02 20:19:13.416513+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (19, 'longest-substring-without-repeating-characters', 'Longest Substring Without Repeating Characters', 'Medium', 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', 'NEETCODE_150', 19, true, '{SLIDING_WINDOW}', '2026-04-02 20:19:13.418806+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (20, 'longest-repeating-character-replacement', 'Longest Repeating Character Replacement', 'Medium', 'https://leetcode.com/problems/longest-repeating-character-replacement/', 'NEETCODE_150', 20, true, '{SLIDING_WINDOW}', '2026-04-02 20:19:13.421137+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (21, 'permutation-in-string', 'Permutation in String', 'Medium', 'https://leetcode.com/problems/permutation-in-string/', 'NEETCODE_150', 21, true, '{SLIDING_WINDOW}', '2026-04-02 20:19:13.423491+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (22, 'minimum-window-substring', 'Minimum Window Substring', 'Hard', 'https://leetcode.com/problems/minimum-window-substring/', 'NEETCODE_150', 22, true, '{SLIDING_WINDOW}', '2026-04-02 20:19:13.425911+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (23, 'sliding-window-maximum', 'Sliding Window Maximum', 'Hard', 'https://leetcode.com/problems/sliding-window-maximum/', 'NEETCODE_150', 23, true, '{SLIDING_WINDOW}', '2026-04-02 20:19:13.428313+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (24, 'valid-parentheses', 'Valid Parentheses', 'Easy', 'https://leetcode.com/problems/valid-parentheses/', 'NEETCODE_150', 24, true, '{STACK}', '2026-04-02 20:19:13.430615+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (25, 'min-stack', 'Min Stack', 'Medium', 'https://leetcode.com/problems/min-stack/', 'NEETCODE_150', 25, true, '{STACK}', '2026-04-02 20:19:13.433253+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (26, 'evaluate-reverse-polish-notation', 'Evaluate Reverse Polish Notation', 'Medium', 'https://leetcode.com/problems/evaluate-reverse-polish-notation/', 'NEETCODE_150', 26, true, '{STACK}', '2026-04-02 20:19:13.435485+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (27, 'generate-parentheses', 'Generate Parentheses', 'Medium', 'https://leetcode.com/problems/generate-parentheses/', 'NEETCODE_150', 27, true, '{STACK}', '2026-04-02 20:19:13.437694+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (28, 'daily-temperatures', 'Daily Temperatures', 'Medium', 'https://leetcode.com/problems/daily-temperatures/', 'NEETCODE_150', 28, true, '{STACK}', '2026-04-02 20:19:13.43997+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (29, 'car-fleet', 'Car Fleet', 'Medium', 'https://leetcode.com/problems/car-fleet/', 'NEETCODE_150', 29, true, '{STACK}', '2026-04-02 20:19:13.442329+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (30, 'largest-rectangle-in-histogram', 'Largest Rectangle in Histogram', 'Hard', 'https://leetcode.com/problems/largest-rectangle-in-histogram/', 'NEETCODE_150', 30, true, '{STACK}', '2026-04-02 20:19:13.444588+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (31, 'reverse-linked-list', 'Reverse Linked List', 'Easy', 'https://leetcode.com/problems/reverse-linked-list/', 'NEETCODE_150', 31, true, '{LINKED_LIST}', '2026-04-02 20:19:13.446876+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (32, 'merge-two-sorted-lists', 'Merge Two Sorted Lists', 'Easy', 'https://leetcode.com/problems/merge-two-sorted-lists/', 'NEETCODE_150', 32, true, '{LINKED_LIST}', '2026-04-02 20:19:13.449124+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (33, 'reorder-list', 'Reorder List', 'Medium', 'https://leetcode.com/problems/reorder-list/', 'NEETCODE_150', 33, true, '{LINKED_LIST}', '2026-04-02 20:19:13.451477+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (34, 'remove-nth-node-from-end-of-list', 'Remove Nth Node From End of List', 'Medium', 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/', 'NEETCODE_150', 34, true, '{LINKED_LIST}', '2026-04-02 20:19:13.453947+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (35, 'copy-list-with-random-pointer', 'Copy List with Random Pointer', 'Medium', 'https://leetcode.com/problems/copy-list-with-random-pointer/', 'NEETCODE_150', 35, true, '{LINKED_LIST}', '2026-04-02 20:19:13.456266+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (36, 'add-two-numbers', 'Add Two Numbers', 'Medium', 'https://leetcode.com/problems/add-two-numbers/', 'NEETCODE_150', 36, true, '{LINKED_LIST}', '2026-04-02 20:19:13.458522+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (37, 'linked-list-cycle', 'Linked List Cycle', 'Easy', 'https://leetcode.com/problems/linked-list-cycle/', 'NEETCODE_150', 37, true, '{LINKED_LIST}', '2026-04-02 20:19:13.460898+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (38, 'find-the-duplicate-number', 'Find the Duplicate Number', 'Medium', 'https://leetcode.com/problems/find-the-duplicate-number/', 'NEETCODE_150', 38, true, '{LINKED_LIST}', '2026-04-02 20:19:13.463392+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (39, 'lru-cache', 'LRU Cache', 'Medium', 'https://leetcode.com/problems/lru-cache/', 'NEETCODE_150', 39, true, '{LINKED_LIST}', '2026-04-02 20:19:13.465645+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (40, 'merge-k-sorted-lists', 'Merge k Sorted Lists', 'Hard', 'https://leetcode.com/problems/merge-k-sorted-lists/', 'NEETCODE_150', 40, true, '{LINKED_LIST}', '2026-04-02 20:19:13.468211+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (41, 'reverse-nodes-in-k-group', 'Reverse Nodes in k-Group', 'Hard', 'https://leetcode.com/problems/reverse-nodes-in-k-group/', 'NEETCODE_150', 41, true, '{LINKED_LIST}', '2026-04-02 20:19:13.470557+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (42, 'number-of-islands', 'Number of Islands', 'Medium', 'https://leetcode.com/problems/number-of-islands/', 'NEETCODE_150', 42, true, '{GRAPH}', '2026-04-02 20:19:13.472925+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (43, 'max-area-of-island', 'Max Area of Island', 'Medium', 'https://leetcode.com/problems/max-area-of-island/', 'NEETCODE_150', 43, true, '{GRAPH}', '2026-04-02 20:19:13.475283+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (44, 'clone-graph', 'Clone Graph', 'Medium', 'https://leetcode.com/problems/clone-graph/', 'NEETCODE_150', 44, true, '{GRAPH}', '2026-04-02 20:19:13.477575+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (45, 'pacific-atlantic-water-flow', 'Pacific Atlantic Water Flow', 'Medium', 'https://leetcode.com/problems/pacific-atlantic-water-flow/', 'NEETCODE_150', 45, true, '{GRAPH}', '2026-04-02 20:19:13.479773+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (46, 'surrounded-regions', 'Surrounded Regions', 'Medium', 'https://leetcode.com/problems/surrounded-regions/', 'NEETCODE_150', 46, true, '{GRAPH}', '2026-04-02 20:19:13.482173+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (47, 'course-schedule', 'Course Schedule', 'Medium', 'https://leetcode.com/problems/course-schedule/', 'NEETCODE_150', 47, true, '{GRAPH}', '2026-04-02 20:19:13.48441+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (48, 'course-schedule-ii', 'Course Schedule II', 'Medium', 'https://leetcode.com/problems/course-schedule-ii/', 'NEETCODE_150', 48, true, '{GRAPH}', '2026-04-02 20:19:13.486645+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (49, 'graph-valid-tree', 'Graph Valid Tree', 'Medium', 'https://leetcode.com/problems/graph-valid-tree/', 'NEETCODE_150', 49, true, '{GRAPH}', '2026-04-02 20:19:13.488982+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (50, 'number-of-connected-components-in-an-undirected-graph', 'Number of Connected Components', 'Medium', 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/', 'NEETCODE_150', 50, true, '{"DSU (Disjoint Set Union)"}', '2026-04-02 20:19:13.49137+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (51, 'redundant-connection', 'Redundant Connection', 'Medium', 'https://leetcode.com/problems/redundant-connection/', 'NEETCODE_150', 51, true, '{"DSU (Disjoint Set Union)"}', '2026-04-02 20:19:13.493641+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (52, 'smallest-string-with-swaps', 'Smallest String With Swaps', 'Medium', 'https://leetcode.com/problems/smallest-string-with-swaps/', 'NEETCODE_150', 52, true, '{"DSU (Disjoint Set Union)"}', '2026-04-02 20:19:13.496+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (53, 'satisfiability-of-equality-equations', 'Satisfiability of Equality Equations', 'Medium', 'https://leetcode.com/problems/satisfiability-of-equality-equations/', 'NEETCODE_150', 53, true, '{"DSU (Disjoint Set Union)"}', '2026-04-02 20:19:13.498331+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (54, 'accounts-merge', 'Accounts Merge', 'Medium', 'https://leetcode.com/problems/accounts-merge/', 'NEETCODE_150', 54, true, '{"DSU (Disjoint Set Union)"}', '2026-04-02 20:19:13.500628+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (56, 'binary-search', 'Binary Search', 'Easy', 'https://leetcode.com/problems/binary-search/', 'NEETCODE_150', 56, true, '{BINARY_SEARCH}', '2026-04-02 20:19:13.503308+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (57, 'search-a-2d-matrix', 'Search a 2D Matrix', 'Medium', 'https://leetcode.com/problems/search-a-2d-matrix/', 'NEETCODE_150', 57, true, '{BINARY_SEARCH}', '2026-04-02 20:19:13.505601+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (58, 'koko-eating-bananas', 'Koko Eating Bananas', 'Medium', 'https://leetcode.com/problems/koko-eating-bananas/', 'NEETCODE_150', 58, true, '{BINARY_SEARCH}', '2026-04-02 20:19:13.508121+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (59, 'find-minimum-in-rotated-sorted-array', 'Find Minimum in Rotated Sorted Array', 'Medium', 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/', 'NEETCODE_150', 59, true, '{BINARY_SEARCH}', '2026-04-02 20:19:13.510479+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (60, 'search-in-rotated-sorted-array', 'Search in Rotated Sorted Array', 'Medium', 'https://leetcode.com/problems/search-in-rotated-sorted-array/', 'NEETCODE_150', 60, true, '{BINARY_SEARCH}', '2026-04-02 20:19:13.512724+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (61, 'time-based-key-value-store', 'Time Based Key-Value Store', 'Medium', 'https://leetcode.com/problems/time-based-key-value-store/', 'NEETCODE_150', 61, true, '{BINARY_SEARCH}', '2026-04-02 20:19:13.514976+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (62, 'median-of-two-sorted-arrays', 'Median of Two Sorted Arrays', 'Hard', 'https://leetcode.com/problems/median-of-two-sorted-arrays/', 'NEETCODE_150', 62, true, '{BINARY_SEARCH}', '2026-04-02 20:19:13.51737+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (63, 'invert-binary-tree', 'Invert Binary Tree', 'Easy', 'https://leetcode.com/problems/invert-binary-tree/', 'NEETCODE_150', 63, true, '{TREE}', '2026-04-02 20:19:13.519674+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (64, 'maximum-depth-of-binary-tree', 'Maximum Depth of Binary Tree', 'Easy', 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', 'NEETCODE_150', 64, true, '{TREE}', '2026-04-02 20:19:13.522053+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (65, 'diameter-of-binary-tree', 'Diameter of Binary Tree', 'Easy', 'https://leetcode.com/problems/diameter-of-binary-tree/', 'NEETCODE_150', 65, true, '{TREE}', '2026-04-02 20:19:13.524381+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (66, 'balanced-binary-tree', 'Balanced Binary Tree', 'Easy', 'https://leetcode.com/problems/balanced-binary-tree/', 'NEETCODE_150', 66, true, '{TREE}', '2026-04-02 20:19:13.526703+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (67, 'same-tree', 'Same Tree', 'Easy', 'https://leetcode.com/problems/same-tree/', 'NEETCODE_150', 67, true, '{TREE}', '2026-04-02 20:19:13.529161+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (68, 'subtree-of-another-tree', 'Subtree of Another Tree', 'Easy', 'https://leetcode.com/problems/subtree-of-another-tree/', 'NEETCODE_150', 68, true, '{TREE}', '2026-04-02 20:19:13.53145+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (69, 'lowest-common-ancestor-of-a-binary-search-tree', 'Lowest Common Ancestor of a BST', 'Easy', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/', 'NEETCODE_150', 69, true, '{TREE}', '2026-04-02 20:19:13.533788+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (70, 'binary-tree-level-order-traversal', 'Binary Tree Level Order Traversal', 'Medium', 'https://leetcode.com/problems/binary-tree-level-order-traversal/', 'NEETCODE_150', 70, true, '{TREE}', '2026-04-02 20:19:13.536098+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (71, 'binary-tree-right-side-view', 'Binary Tree Right Side View', 'Medium', 'https://leetcode.com/problems/binary-tree-right-side-view/', 'NEETCODE_150', 71, true, '{TREE}', '2026-04-02 20:19:13.538522+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (72, 'count-good-nodes-in-binary-tree', 'Count Good Nodes in Binary Tree', 'Medium', 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/', 'NEETCODE_150', 72, true, '{TREE}', '2026-04-02 20:19:13.5408+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (73, 'validate-binary-search-tree', 'Validate Binary Search Tree', 'Medium', 'https://leetcode.com/problems/validate-binary-search-tree/', 'NEETCODE_150', 73, true, '{TREE}', '2026-04-02 20:19:13.543088+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (74, 'kth-smallest-element-in-a-bst', 'Kth Smallest Element in a BST', 'Medium', 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/', 'NEETCODE_150', 74, true, '{TREE}', '2026-04-02 20:19:13.545434+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (75, 'construct-binary-tree-from-preorder-and-inorder-traversal', 'Construct Binary Tree from Preorder and Inorder Traversal', 'Medium', 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/', 'NEETCODE_150', 75, true, '{TREE}', '2026-04-02 20:19:13.547675+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (76, 'binary-tree-maximum-path-sum', 'Binary Tree Maximum Path Sum', 'Hard', 'https://leetcode.com/problems/binary-tree-maximum-path-sum/', 'NEETCODE_150', 76, true, '{TREE}', '2026-04-02 20:19:13.550176+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (77, 'serialize-and-deserialize-binary-tree', 'Serialize and Deserialize Binary Tree', 'Hard', 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', 'NEETCODE_150', 77, true, '{TREE}', '2026-04-02 20:19:13.552501+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (78, 'kth-largest-element-in-a-stream', 'Kth Largest Element in a Stream', 'Easy', 'https://leetcode.com/problems/kth-largest-element-in-a-stream/', 'NEETCODE_150', 78, true, '{HEAP}', '2026-04-02 20:19:13.554805+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (79, 'last-stone-weight', 'Last Stone Weight', 'Easy', 'https://leetcode.com/problems/last-stone-weight/', 'NEETCODE_150', 79, true, '{HEAP}', '2026-04-02 20:19:13.557096+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (80, 'k-closest-points-to-origin', 'K Closest Points to Origin', 'Medium', 'https://leetcode.com/problems/k-closest-points-to-origin/', 'NEETCODE_150', 80, true, '{HEAP}', '2026-04-02 20:19:13.55963+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (81, 'kth-largest-element-in-an-array', 'Kth Largest Element in an Array', 'Medium', 'https://leetcode.com/problems/kth-largest-element-in-an-array/', 'NEETCODE_150', 81, true, '{HEAP}', '2026-04-02 20:19:13.562086+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (82, 'task-scheduler', 'Task Scheduler', 'Medium', 'https://leetcode.com/problems/task-scheduler/', 'NEETCODE_150', 82, true, '{HEAP}', '2026-04-02 20:19:13.564404+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (83, 'design-twitter', 'Design Twitter', 'Medium', 'https://leetcode.com/problems/design-twitter/', 'NEETCODE_150', 83, true, '{HEAP}', '2026-04-02 20:19:13.56674+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (84, 'find-median-from-data-stream', 'Find Median from Data Stream', 'Hard', 'https://leetcode.com/problems/find-median-from-data-stream/', 'NEETCODE_150', 84, true, '{HEAP}', '2026-04-02 20:19:13.56901+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (85, 'subsets', 'Subsets', 'Medium', 'https://leetcode.com/problems/subsets/', 'NEETCODE_150', 85, true, '{BACKTRACKING}', '2026-04-02 20:19:13.571496+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (86, 'combination-sum', 'Combination Sum', 'Medium', 'https://leetcode.com/problems/combination-sum/', 'NEETCODE_150', 86, true, '{BACKTRACKING}', '2026-04-02 20:19:13.573794+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (87, 'permutations', 'Permutations', 'Medium', 'https://leetcode.com/problems/permutations/', 'NEETCODE_150', 87, true, '{BACKTRACKING}', '2026-04-02 20:19:13.576253+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (88, 'subsets-ii', 'Subsets II', 'Medium', 'https://leetcode.com/problems/subsets-ii/', 'NEETCODE_150', 88, true, '{BACKTRACKING}', '2026-04-02 20:19:13.580102+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (89, 'combination-sum-ii', 'Combination Sum II', 'Medium', 'https://leetcode.com/problems/combination-sum-ii/', 'NEETCODE_150', 89, true, '{BACKTRACKING}', '2026-04-02 20:19:13.582474+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (90, 'word-search', 'Word Search', 'Medium', 'https://leetcode.com/problems/word-search/', 'NEETCODE_150', 90, true, '{BACKTRACKING}', '2026-04-02 20:19:13.584812+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (91, 'palindrome-partitioning', 'Palindrome Partitioning', 'Medium', 'https://leetcode.com/problems/palindrome-partitioning/', 'NEETCODE_150', 91, true, '{BACKTRACKING}', '2026-04-02 20:19:13.587132+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (92, 'letter-combinations-of-a-phone-number', 'Letter Combinations of a Phone Number', 'Medium', 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/', 'NEETCODE_150', 92, true, '{BACKTRACKING}', '2026-04-02 20:19:13.589375+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (93, 'n-queens', 'N-Queens', 'Hard', 'https://leetcode.com/problems/n-queens/', 'NEETCODE_150', 93, true, '{BACKTRACKING}', '2026-04-02 20:19:13.591788+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (94, 'implement-trie-prefix-tree', 'Implement Trie (Prefix Tree)', 'Medium', 'https://leetcode.com/problems/implement-trie-prefix-tree/', 'NEETCODE_150', 94, true, '{TRIE}', '2026-04-02 20:19:13.59422+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (95, 'design-add-and-search-words-data-structure', 'Design Add and Search Words Data Structure', 'Medium', 'https://leetcode.com/problems/design-add-and-search-words-data-structure/', 'NEETCODE_150', 95, true, '{TRIE}', '2026-04-02 20:19:13.596581+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (96, 'word-search-ii', 'Word Search II', 'Hard', 'https://leetcode.com/problems/word-search-ii/', 'NEETCODE_150', 96, true, '{TRIE}', '2026-04-02 20:19:13.59887+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (97, 'word-ladder', 'Word Ladder', 'Hard', 'https://leetcode.com/problems/word-ladder/', 'NEETCODE_150', 97, true, '{GRAPH}', '2026-04-02 20:19:13.601254+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (98, 'min-cost-to-connect-all-points', 'Min Cost to Connect All Points', 'Medium', 'https://leetcode.com/problems/min-cost-to-connect-all-points/', 'NEETCODE_150', 98, true, '{GRAPH}', '2026-04-02 20:19:13.603645+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (99, 'network-delay-time', 'Network Delay Time', 'Medium', 'https://leetcode.com/problems/network-delay-time/', 'NEETCODE_150', 99, true, '{GRAPH}', '2026-04-02 20:19:13.605972+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (100, 'swim-in-rising-water', 'Swim in Rising Water', 'Hard', 'https://leetcode.com/problems/swim-in-rising-water/', 'NEETCODE_150', 100, true, '{GRAPH}', '2026-04-02 20:19:13.608208+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (101, 'alien-dictionary', 'Alien Dictionary', 'Hard', 'https://leetcode.com/problems/alien-dictionary/', 'NEETCODE_150', 101, true, '{"DSU (Disjoint Set Union)"}', '2026-04-02 20:19:13.610433+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (102, 'cheapest-flights-within-k-stops', 'Cheapest Flights Within K Stops', 'Medium', 'https://leetcode.com/problems/cheapest-flights-within-k-stops/', 'NEETCODE_150', 102, true, '{GRAPH}', '2026-04-02 20:19:13.61279+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (103, 'climbing-stairs', 'Climbing Stairs', 'Easy', 'https://leetcode.com/problems/climbing-stairs/', 'NEETCODE_150', 103, true, '{DP_1D}', '2026-04-02 20:19:13.615076+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (104, 'min-cost-climbing-stairs', 'Min Cost Climbing Stairs', 'Easy', 'https://leetcode.com/problems/min-cost-climbing-stairs/', 'NEETCODE_150', 104, true, '{DP_1D}', '2026-04-02 20:19:13.617411+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (105, 'house-robber', 'House Robber', 'Medium', 'https://leetcode.com/problems/house-robber/', 'NEETCODE_150', 105, true, '{DP_1D}', '2026-04-02 20:19:13.619641+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (106, 'house-robber-ii', 'House Robber II', 'Medium', 'https://leetcode.com/problems/house-robber-ii/', 'NEETCODE_150', 106, true, '{DP_1D}', '2026-04-02 20:19:13.621894+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (107, 'longest-palindromic-substring', 'Longest Palindromic Substring', 'Medium', 'https://leetcode.com/problems/longest-palindromic-substring/', 'NEETCODE_150', 107, true, '{DP_1D}', '2026-04-02 20:19:13.624085+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (108, 'palindromic-substrings', 'Palindromic Substrings', 'Medium', 'https://leetcode.com/problems/palindromic-substrings/', 'NEETCODE_150', 108, true, '{DP_1D}', '2026-04-02 20:19:13.62642+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (109, 'decode-ways', 'Decode Ways', 'Medium', 'https://leetcode.com/problems/decode-ways/', 'NEETCODE_150', 109, true, '{DP_1D}', '2026-04-02 20:19:13.628757+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (110, 'coin-change', 'Coin Change', 'Medium', 'https://leetcode.com/problems/coin-change/', 'NEETCODE_150', 110, true, '{DP_1D}', '2026-04-02 20:19:13.631089+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (111, 'maximum-product-subarray', 'Maximum Product Subarray', 'Medium', 'https://leetcode.com/problems/maximum-product-subarray/', 'NEETCODE_150', 111, true, '{DP_1D}', '2026-04-02 20:19:13.633324+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (112, 'word-break', 'Word Break', 'Medium', 'https://leetcode.com/problems/word-break/', 'NEETCODE_150', 112, true, '{DP_1D}', '2026-04-02 20:19:13.635529+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (113, 'longest-increasing-subsequence', 'Longest Increasing Subsequence', 'Medium', 'https://leetcode.com/problems/longest-increasing-subsequence/', 'NEETCODE_150', 113, true, '{DP_1D}', '2026-04-02 20:19:13.637795+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (114, 'partition-equal-subset-sum', 'Partition Equal Subset Sum', 'Medium', 'https://leetcode.com/problems/partition-equal-subset-sum/', 'NEETCODE_150', 114, true, '{DP_1D}', '2026-04-02 20:19:13.640124+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (115, 'unique-paths', 'Unique Paths', 'Medium', 'https://leetcode.com/problems/unique-paths/', 'NEETCODE_150', 115, true, '{DP_2D}', '2026-04-02 20:19:13.642426+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (116, 'longest-common-subsequence', 'Longest Common Subsequence', 'Medium', 'https://leetcode.com/problems/longest-common-subsequence/', 'NEETCODE_150', 116, true, '{DP_2D}', '2026-04-02 20:19:13.644735+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (117, 'best-time-to-buy-and-sell-stock-with-cooldown', 'Best Time to Buy and Sell Stock with Cooldown', 'Medium', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/', 'NEETCODE_150', 117, true, '{DP_2D}', '2026-04-02 20:19:13.647199+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (118, 'coin-change-ii', 'Coin Change II', 'Medium', 'https://leetcode.com/problems/coin-change-ii/', 'NEETCODE_150', 118, true, '{DP_2D}', '2026-04-02 20:19:13.649461+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (119, 'target-sum', 'Target Sum', 'Medium', 'https://leetcode.com/problems/target-sum/', 'NEETCODE_150', 119, true, '{DP_2D}', '2026-04-02 20:19:13.65173+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (120, 'interleaving-string', 'Interleaving String', 'Medium', 'https://leetcode.com/problems/interleaving-string/', 'NEETCODE_150', 120, true, '{DP_2D}', '2026-04-02 20:19:13.653995+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (121, 'longest-increasing-path-in-a-matrix', 'Longest Increasing Path in a Matrix', 'Hard', 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/', 'NEETCODE_150', 121, true, '{DP_2D}', '2026-04-02 20:19:13.656409+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (122, 'distinct-subsequences', 'Distinct Subsequences', 'Hard', 'https://leetcode.com/problems/distinct-subsequences/', 'NEETCODE_150', 122, true, '{DP_2D}', '2026-04-02 20:19:13.658854+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (123, 'edit-distance', 'Edit Distance', 'Hard', 'https://leetcode.com/problems/edit-distance/', 'NEETCODE_150', 123, true, '{DP_2D}', '2026-04-02 20:19:13.661138+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (124, 'burst-balloons', 'Burst Balloons', 'Hard', 'https://leetcode.com/problems/burst-balloons/', 'NEETCODE_150', 124, true, '{DP_2D}', '2026-04-02 20:19:13.66347+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (125, 'regular-expression-matching', 'Regular Expression Matching', 'Hard', 'https://leetcode.com/problems/regular-expression-matching/', 'NEETCODE_150', 125, true, '{DP_2D}', '2026-04-02 20:19:13.665756+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (126, 'maximum-subarray', 'Maximum Subarray', 'Easy', 'https://leetcode.com/problems/maximum-subarray/', 'NEETCODE_150', 126, true, '{GREEDY}', '2026-04-02 20:19:13.668234+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (127, 'jump-game', 'Jump Game', 'Medium', 'https://leetcode.com/problems/jump-game/', 'NEETCODE_150', 127, true, '{GREEDY}', '2026-04-02 20:19:13.670596+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (128, 'jump-game-ii', 'Jump Game II', 'Medium', 'https://leetcode.com/problems/jump-game-ii/', 'NEETCODE_150', 128, true, '{GREEDY}', '2026-04-02 20:19:13.672885+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (129, 'gas-station', 'Gas Station', 'Medium', 'https://leetcode.com/problems/gas-station/', 'NEETCODE_150', 129, true, '{GREEDY}', '2026-04-02 20:19:13.675211+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (130, 'hand-of-straights', 'Hand of Straights', 'Medium', 'https://leetcode.com/problems/hand-of-straights/', 'NEETCODE_150', 130, true, '{GREEDY}', '2026-04-02 20:19:13.677542+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (131, 'merge-triplets-to-form-target-triplets', 'Merge Triplets to Form Target Triplets', 'Medium', 'https://leetcode.com/problems/merge-triplets-to-form-target-triplets/', 'NEETCODE_150', 131, true, '{GREEDY}', '2026-04-02 20:19:13.679994+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (132, 'partition-labels', 'Partition Labels', 'Medium', 'https://leetcode.com/problems/partition-labels/', 'NEETCODE_150', 132, true, '{GREEDY}', '2026-04-02 20:19:13.682289+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (133, 'valid-parenthesis-string', 'Valid Parenthesis String', 'Medium', 'https://leetcode.com/problems/valid-parenthesis-string/', 'NEETCODE_150', 133, true, '{GREEDY}', '2026-04-02 20:19:13.684686+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (134, 'insert-interval', 'Insert Interval', 'Medium', 'https://leetcode.com/problems/insert-interval/', 'NEETCODE_150', 134, true, '{INTERVALS}', '2026-04-02 20:19:13.686947+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (135, 'merge-intervals', 'Merge Intervals', 'Medium', 'https://leetcode.com/problems/merge-intervals/', 'NEETCODE_150', 135, true, '{INTERVALS}', '2026-04-02 20:19:13.689155+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (136, 'non-overlapping-intervals', 'Non-overlapping Intervals', 'Medium', 'https://leetcode.com/problems/non-overlapping-intervals/', 'NEETCODE_150', 136, true, '{INTERVALS}', '2026-04-02 20:19:13.691348+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (137, 'meeting-rooms', 'Meeting Rooms', 'Easy', 'https://leetcode.com/problems/meeting-rooms/', 'NEETCODE_150', 137, true, '{INTERVALS}', '2026-04-02 20:19:13.693537+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (138, 'meeting-rooms-ii', 'Meeting Rooms II', 'Medium', 'https://leetcode.com/problems/meeting-rooms-ii/', 'NEETCODE_150', 138, true, '{INTERVALS}', '2026-04-02 20:19:13.695695+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (139, 'minimum-interval-to-include-each-query', 'Minimum Interval to Include Each Query', 'Hard', 'https://leetcode.com/problems/minimum-interval-to-include-each-query/', 'NEETCODE_150', 139, true, '{INTERVALS}', '2026-04-02 20:19:13.697945+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (140, 'single-number', 'Single Number', 'Easy', 'https://leetcode.com/problems/single-number/', 'NEETCODE_150', 140, true, '{BIT_MANIPULATION}', '2026-04-02 20:19:13.700609+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (141, 'number-of-1-bits', 'Number of 1 Bits', 'Easy', 'https://leetcode.com/problems/number-of-1-bits/', 'NEETCODE_150', 141, true, '{BIT_MANIPULATION}', '2026-04-02 20:19:13.702881+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (142, 'counting-bits', 'Counting Bits', 'Easy', 'https://leetcode.com/problems/counting-bits/', 'NEETCODE_150', 142, true, '{BIT_MANIPULATION}', '2026-04-02 20:19:13.705265+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (143, 'reverse-bits', 'Reverse Bits', 'Easy', 'https://leetcode.com/problems/reverse-bits/', 'NEETCODE_150', 143, true, '{BIT_MANIPULATION}', '2026-04-02 20:19:13.707639+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (144, 'missing-number', 'Missing Number', 'Easy', 'https://leetcode.com/problems/missing-number/', 'NEETCODE_150', 144, true, '{BIT_MANIPULATION}', '2026-04-02 20:19:13.709996+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (145, 'sum-of-two-integers', 'Sum of Two Integers', 'Medium', 'https://leetcode.com/problems/sum-of-two-integers/', 'NEETCODE_150', 145, true, '{BIT_MANIPULATION}', '2026-04-02 20:19:13.712467+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (146, 'reverse-integer', 'Reverse Integer', 'Medium', 'https://leetcode.com/problems/reverse-integer/', 'NEETCODE_150', 146, true, '{BIT_MANIPULATION}', '2026-04-02 20:19:13.714693+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (147, 'rotate-image', 'Rotate Image', 'Medium', 'https://leetcode.com/problems/rotate-image/', 'NEETCODE_150', 147, true, '{MATH&GEOMETRY}', '2026-04-02 20:19:13.716994+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (148, 'spiral-matrix', 'Spiral Matrix', 'Medium', 'https://leetcode.com/problems/spiral-matrix/', 'NEETCODE_150', 148, true, '{MATH&GEOMETRY}', '2026-04-02 20:19:13.719185+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (149, 'set-matrix-zeroes', 'Set Matrix Zeroes', 'Medium', 'https://leetcode.com/problems/set-matrix-zeroes/', 'NEETCODE_150', 149, true, '{MATH&GEOMETRY}', '2026-04-02 20:19:13.721472+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (150, 'happy-number', 'Happy Number', 'Easy', 'https://leetcode.com/problems/happy-number/', 'NEETCODE_150', 150, true, '{MATH&GEOMETRY}', '2026-04-02 20:19:13.72375+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (151, 'plus-one', 'Plus One', 'Easy', 'https://leetcode.com/problems/plus-one/', 'NEETCODE_150', 151, true, '{MATH&GEOMETRY}', '2026-04-02 20:19:13.726108+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (152, 'powx-n', 'Pow(x,n)', 'Medium', 'https://leetcode.com/problems/powx-n/', 'NEETCODE_150', 152, true, '{MATH&GEOMETRY}', '2026-04-02 20:19:13.728453+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (153, 'multiply-strings', 'Multiply Strings', 'Medium', 'https://leetcode.com/problems/multiply-strings/', 'NEETCODE_150', 153, true, '{MATH&GEOMETRY}', '2026-04-02 20:19:13.730768+00');
INSERT INTO public.problems (id, slug, title, difficulty, url, source_set, queue_rank, active, tags, created_at) VALUES (154, 'detect-squares', 'Detect Squares', 'Medium', 'https://leetcode.com/problems/detect-squares/', 'NEETCODE_150', 154, true, '{MATH&GEOMETRY}', '2026-04-02 20:19:13.733183+00');


--
-- Name: problems_id_seq; Type: SEQUENCE SET; Schema: public; Owner: queue_up
--

SELECT pg_catalog.setval('public.problems_id_seq', 154, true);


--
-- PostgreSQL database dump complete
--

